openapi: 3.0.3

info:
  version: 1.0.0
  title: Gesti√≥n de Clientes

servers:
  - url: http://127.0.0.1:80/api/v1

tags:
  - name: Cliente
    description: Cliente 

paths:
  /clientes: 
    $ref: 'clientes.yaml'
  /clientes/{cliente_id}:
    $ref: 'clientes_id.yaml'

components:
  schemas:
    Cliente:
      $ref: 'schemas.yaml#/Cliente'
    Id_Cliente:
      $ref: 'schemas.yaml#/Id_Cliente'
    DNI_Cliente:
      $ref: 'schemas.yaml#/DNI_Cliente'
    Nombre_Cliente:
      $ref: 'schemas.yaml#/Nombre_Cliente'
    Apellidos_Cliente:
      $ref: 'schemas.yaml#/Apellidos_Cliente'
    Direccion_Cliente:
      $ref: 'schemas.yaml#/Direccion_Cliente'
    CuentaBancaria_Cliente:
      $ref: 'schemas.yaml#/CuentaBancaria_Cliente'
    Telefono_Cliente:
      $ref: 'schemas.yaml#/Telefono_Cliente'
    Email_Cliente:
      $ref: 'schemas.yaml#/Email_Cliente'
      
    HTTP_Problem:
      $ref: 'schemas.yaml#/HTTP_Problem'
    Link:
      $ref: 'schemas.yaml#/Link'
  
